// File generated by `flutterfire configure`.
// This file will be automatically generated when you run `flutterfire configure`.
// 
// To generate this file manually, run:
//   flutterfire configure
//
// Or follow the manual setup instructions in FIREBASE_SETUP.md

// This is a placeholder. Run `flutterfire configure` to generate the actual file.

